### ISSUE TITLE
Support for QuickPay API v10

### ISSUE THREAD

**Issue by ta** [QuickPay/active_merchant#1]
ActiveMerchant (AM) currently supports QuickPay API [v7](http://doc.quickpay.net/api.html) and we need to **also** support [v10](http://tech.quickpay.net/api/) - that is both versions should be supported at the same time. Which version to use should be configurable for every AM user.

I'm not sure how to do this. A Shopify guy mentioned that "AM requests a md5 checksum and it should be possible to use the same mechanism to ask for API-version".

**Comment by benee** [comment]
already done
